### ISSUE TITLE
Resource creation/cleanup for OpenStack not ideal

### ISSUE THREAD

**Issue by toabctl** [SUSE-Cloud/socok8s#150]
When following the documentation (from https://github.com/SUSE-Cloud/socok8s/blob/master/doc/source/deploy-guide/prepare-localhost.rst#configure-openstack-deployment-mechanism) to setup an env in a OpenStack cloud, it's easy to create mutliple resources with the same name (eg `$prefix-net`) simply by doing the steps more than once (I did because I forgot that I did the same steps with the same $prefix month ago).
In that case, you get errors during the deployment (resource not unique). Also cleaning up the resources is not that easy (find out the ID, list ports, ...).

This is problematic because it makes resource cleanup difficult and we are already running out of resources.
Using a heat stack would solve that problem imo.

**Comment by evrardjp** [comment]
Using unique names would work too. This is in the plan for CI, which is required anyway :)
Ofc we can have our own stack too.

**Comment by toabctl** [comment]
> Using unique names would work too. This is in the plan for CI, which is required anyway :)

Sure. But the cleanup is still problemmatic. Heat already solved that problem for us.

**Comment by toabctl** [comment]
I think this got solved already
