### ISSUE TITLE
README and doc/ have the same information

### ISSUE THREAD

**Issue by toabctl** [SUSE-Cloud/socok8s#151]
README.rst and the doc/ folder have similiar information. Would be good to cleanup README so the doc content is only in the doc/ folder.

Eg. https://github.com/SUSE-Cloud/socok8s/blob/master/doc/source/deploy-guide/prepare-localhost.rst#configure-openstack-deployment-mechanism and https://github.com/SUSE-Cloud/socok8s#configure-engcloud

**Comment by evrardjp** [comment]
This is due to a recent merge regression. I have discussed this on the channel, but got no answer on _when_ this will be solved.
