### ISSUE TITLE
failure to copy hosts.yml file

### ISSUE THREAD

**Issue by Itxaka** [SUSE-Cloud/socok8s#82]
Due to https://github.com/SUSE-Cloud/socok8s/blob/master/script_library/run-ansible.sh#L17 it will only check if the dir exists but if the dir exists but not the host.yml file, the deployment will fail during "Extend inventory in workspace with newly created SES node" which uses that host.yml file.

This should individually check if the dir exists AND if the hosts.yml exists inside the dir

Writing it down so I dont forget to send a PR later.

**Comment by jsuchome** [comment]
While the correct teardown removes whole directory, so it is not such a big deal, I agree

**Comment by evrardjp** [comment]
That should be solved nowadays IIRC.

**Comment by Itxaka** [comment]
it is, closing
